nginx:
    restart: "no"
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
    ports:
        - "81:80"

node1:
    restart: always
    build: ./flask
    links:
        - database
    ports:
        - "8081:8000"
    environment:
        - JENKINS_NODES_USAGE_DB_USERNAME=test
        - JENKINS_NODES_USAGE_DB_PASSWORD=123
        - DATABASE_NAME=jenkins

node2:
    restart: always
    build: ./flask
    links:
        - database
    ports:
        - "8082:8000"
    environment:
        - JENKINS_NODES_USAGE_DB_USERNAME=test
        - JENKINS_NODES_USAGE_DB_PASSWORD=123
        - DATABASE_NAME=jenkins

database:
    restart: "no"
    build: ./database
    ports:
        - "31234:5432"